sudo: false

language: scala

matrix:
  include:
  - scala: 2.11.12
    env: PLAY_VERSION=2.5
  - scala: 2.11.12
    env: PLAY_VERSION=2.6
  - scala: 2.12.8
    env: PLAY_VERSION=2.6
  - scala: 2.12.12
    env: PLAY_VERSION=2.7


jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.ivy2/cache'
    